alter table public.exam_config
  add column if not exists attendance_is_active boolean not null default false,
  add column if not exists attendance_code text,
  add column if not exists attendance_date date,
  add column if not exists attendance_generated_at timestamptz;

create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  attendance_date date not null,
  attendance_code text not null,
  marked_at timestamptz not null default now(),
  unique (profile_id, attendance_date)
);

alter table public.attendance_records enable row level security;

drop policy if exists "Students can mark their own attendance" on public.attendance_records;
create policy "Students can mark their own attendance"
  on public.attendance_records for insert
  to authenticated
  with check (auth.uid() = profile_id);

drop policy if exists "Students can read their own attendance" on public.attendance_records;
create policy "Students can read their own attendance"
  on public.attendance_records for select
  to authenticated
  using (auth.uid() = profile_id);

drop policy if exists "Teachers can read attendance" on public.attendance_records;
create policy "Teachers can read attendance"
  on public.attendance_records for select
  to authenticated
  using (exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'teacher'
  ));